/**
 * HimuOperatingSystem
 *
 * File: ex/user_regression_anchors.h
 * Description: User-runtime serial-log anchors used by regression profiles.
 * Copyright(c) 2024-2026 HimuOS, ONLY FOR EDUCATIONAL PURPOSES.
 */

#pragma once

#define EX_USER_REGRESSION_LOG_ENTER_USER_MODE          "[USERBOOT] enter user mode"
#define EX_USER_REGRESSION_LOG_P1_FIRST_ENTRY           EX_USER_REGRESSION_LOG_ENTER_USER_MODE
#define EX_USER_REGRESSION_LOG_TIMER_FROM_USER_FORMAT   "[USERBOOT] timer from user #%u"
#define EX_USER_REGRESSION_LOG_P1_GATE_ARMED            "[USERBOOT] P1 gate armed"
#define EX_USER_REGRESSION_LOG_HELLO                    "[USERBOOT] hello"
#define EX_USER_REGRESSION_LOG_INVALID_RAW_WRITE        "[USERBOOT] invalid raw write rejected"
#define EX_USER_REGRESSION_LOG_HELLO_WRITE_SUCCEEDED    "[USERBOOT] hello write succeeds"
#define EX_USER_REGRESSION_LOG_SYS_RAW_EXIT             "[USERBOOT] SYS_RAW_EXIT"
#define EX_USER_REGRESSION_LOG_SYS_EXIT                 "[USERBOOT] SYS_EXIT"
#define EX_USER_REGRESSION_LOG_INVALID_SYSCALL          "[USERBOOT] invalid raw syscall"
#define EX_USER_REGRESSION_LOG_INVALID_CAP_SYSCALL      "[USERCAP] invalid capability syscall"
#define EX_USER_REGRESSION_LOG_CAP_WRITE_SUCCEEDED      "[USERCAP] stdout capability write succeeds"
#define EX_USER_REGRESSION_LOG_CAP_CLOSE_SUCCEEDED      "[USERCAP] SYS_CLOSE succeeded"
#define EX_USER_REGRESSION_LOG_CAP_WAIT_SUCCEEDED       "[USERCAP] SYS_WAIT_ONE succeeded"
#define EX_USER_REGRESSION_LOG_CAP_WAIT_TIMED_OUT       "[USERCAP] SYS_WAIT_ONE timed out"
#define EX_USER_REGRESSION_LOG_CAP_REJECTED             "[USERCAP] capability syscall rejected"
#define EX_USER_REGRESSION_LOG_READLINE_SUCCEEDED       "[USERINPUT] SYS_READLINE succeeded"
#define EX_USER_REGRESSION_LOG_READLINE_REJECTED        "[USERINPUT] SYS_READLINE rejected"
#define EX_USER_REGRESSION_LOG_SPAWN_PROGRAM_SUCCEEDED  "[DEMOSHELL] SYS_SPAWN_PROGRAM succeeded"
#define EX_USER_REGRESSION_LOG_SPAWN_PROGRAM_REJECTED   "[DEMOSHELL] SYS_SPAWN_PROGRAM rejected"
#define EX_USER_REGRESSION_LOG_WAIT_PID_SUCCEEDED       "[DEMOSHELL] SYS_WAIT_PID succeeded"
#define EX_USER_REGRESSION_LOG_WAIT_PID_REJECTED        "[DEMOSHELL] SYS_WAIT_PID rejected"
#define EX_USER_REGRESSION_LOG_SLEEP_MS_SUCCEEDED       "[DEMOSHELL] SYS_SLEEP_MS succeeded"
#define EX_USER_REGRESSION_LOG_SLEEP_MS_REJECTED        "[DEMOSHELL] SYS_SLEEP_MS rejected"
#define EX_USER_REGRESSION_LOG_KILL_PID_SUCCEEDED       "[DEMOSHELL] SYS_KILL_PID succeeded"
#define EX_USER_REGRESSION_LOG_KILL_PID_REJECTED        "[DEMOSHELL] SYS_KILL_PID rejected"
#define EX_USER_REGRESSION_LOG_QUERY_SYSINFO_SUCCEEDED  "[SYSINFO] SYS_QUERY_SYSINFO succeeded"
#define EX_USER_REGRESSION_LOG_QUERY_SYSINFO_REJECTED   "[SYSINFO] SYS_QUERY_SYSINFO rejected"
#define EX_USER_REGRESSION_LOG_KILL_EXIT                "[DEMOSHELL] kill exit"
#define EX_USER_REGRESSION_LOG_INVALID_USER_BUFFER      "[USERBOOT] invalid user buffer"
#define EX_USER_REGRESSION_LOG_TEARDOWN_FAILED          "[USERBOOT] bootstrap teardown failed"
#define EX_USER_REGRESSION_LOG_TEARDOWN_COMPLETE        "[USERBOOT] bootstrap teardown complete"
#define EX_USER_REGRESSION_LOG_THREAD_TERMINATED_FORMAT "[SCHED] Thread %u terminated"
#define EX_USER_REGRESSION_LOG_IDLE_REAPER              "[USERBOOT] idle/reaper reclaimed user_hello thread"
